function [FF1,F]=RA_get_exposure_local_More(TradingDay,conn)
% conn=connect_jydb();
% setdbprefs('datareturnformat','table')
str1=sprintf(['select cast(convert(varchar(8),A.TradingDay,112) as Int) as TradingDay  '...
    ',A.InnerCode  '...
    ',A.MktCap '...
    ',B.Compu_t '...
    ',A.Size  '...
    ',A.Beta  '...
    ',A.ShortMomentum  '...
    ',A.WeightedMomentum  '...
    ',A.Vol  '...
    ',A.Liquidity '...
    ',A.BP '...
    ',A.FirstIndustryCode  '...
    ',Fwd1Ret as Ret '...
    ',CFO2EV '...
    ',EBITDA2EV '...
    ',E2P '...
    ',FE2P '...
    ',BB2P '...
    ',BB2EV '...
    ',B2P '...
    ',S2EV '...
    ',RNOA '...
    ',CFROI '...
    ',OL2S '...
    ',OLinc '...
    ',WAinc '...
    ',WLinc '...
    ',NCOinc '...
    ',icapx '...
    ',CapxG '...
    ',XF '...
    ',GoodwillInc '...
    ',CFO2S '...
    ',CFI2S '...
    ',CFF2S '...
    ',ShareInc '...
    ',Ret1 '...
    ',Ret9 '...
    ',adjRet '...
    ',Ret6 '...
    ',Ret12 '...
    'from ShengYunDB..RM_StockRiskExposure A  '...
    'inner join ShengYunDB..RR_300_Signal B '...
    'on A.InnerCode=B.InnerCode and B.Compu_t is not null '...
    'and A.TradingDay=''%s'' '...
    'and B.TradingDay=(select MAX(TradingDay) from ShengYunDB..RR_300_Signal where TradingDay<=A.TradingDay) '...
    'left join ShengYunDB..StockDailyTrading C '...
    'on C.InnerCode=A.InnerCode '...
    'and C.TradingDay=A.TradingDay '...
    'left join ShengYunDB..QianAlphaFactorAllDaily D '...
    'on D.InnerCode=A.InnerCode '...
    'and D.TradingDay=A.TradingDay '...
    'order by A.TradingDay,A.InnerCode  '...
    ],TradingDay);
curs=exec(conn, str1);
curs1=fetch(curs);
FF1 = curs1.Data;
F=FF1;
%% �ȱʧֵ
try
    ICut=isnan(F.FirstIndustryCode);
    F(ICut,:)=[];
catch err
end
