function StockRiskRaw=Optimizer_GetStockRiskRaw(conn,DateT)
setdbprefs('datareturnformat','table')
str1=sprintf(['select cast(convert(varchar(8),A.TradingDay,112) as Int) as TradingDay '...
    ',A.InnerCode '...
    ',A.FirstIndustryCode '...
    ',A.Size '...
    ',A.Beta '...
    ',A.ShortMomentum '...
    ',A.WeightedMomentum '...
    ',A.Vol '...
    ',A.Liquidity '...
    ',A.BP '...
    ',A.NLSIZE '...
    ',A.MktCap '...
    ',SpecificReturn '...
    ',SpecificSTD_LT '...
    ',case when left(B.SecuCode,1)=''6'' then 1 else 0 end as MktCode '...
    'from ShengYunDB..RM_StockRiskExposure A '...
    'left join ShengYunDB..StockDailyTrading B '...
    'on A.TradingDay=B.TradingDay and A.InnerCode=B.InnerCode '...
    'where  A.TradingDay>=''%s'' '...
    'order by A.TradingDay,A.InnerCode '...
    ],DateT);
curs=exec(conn, str1);
curs1=fetch(curs);
StockRiskRaw = curs1.Data;