%%
addpath('E:\work\MyClass\Optimizer');

Input=struct();
Input.Risks=struct();
Input.Cons=struct();
Input.Cons.Inds=[-0.5/100,0.5/100];
Input.Cons.SingleStock=[-1.5/100,1.5/100];
Input.Cons.Styles=struct();
Input.Cons.Styles.Size=[-0.6,0.6];
Input.Cons.Styles.NLSize=[-0.6,0.6];
Input.Cons.Styles.Beta=[-0.2,0.2];
Input.Paras.AveR=5e-4;
Input.Paras.RiskMult=10;
Input.Paras.AlphaMult=20;
Input.Paras.Turnover=0.25;
Input.PreviousHolding=[];
Input.InvestU=[];
Input.NonTradeU=[];
%%
conn=connect_jydb();
DateT='2017-01-01';
% str1=sprintf(['select *  '...
%     'from ShengYunDB..V_RM_Opt300HoldCap  '...
%      ]);
% curs=exec(conn, str1);
% curs=fetch(curs);
% HoldCap = curs.Data;
% OptPortOld=[HoldCap.InnerCode,HoldCap.Cap/sum(HoldCap.Cap)];
% DateT='2017-08-11';
%
% PortWeight=xlsread('E:\work\日内跟踪\关注组合\300\OldSignal\Opt\PortWeightTest.xlsx',1);
% OptPortOld=PortWeight(PortWeight(:,1)==max(PortWeight(:,1)),2:3);
% DateT=datestr(datenum(num2str(PortWeight(end,1)),'yyyymmdd'),'yyyy-mm-dd');
% Input.PreviousHolding=OptPortOld;
%% Investment U
str1=sprintf(['select cast(convert(varchar(8),A.TradingDay,112) as Int) as TradingDay,InnerCode  '...
    'from ShengYunDB..StatFM_InvestmentUniverse_300 A order by TradingDay,InnerCode  '...
         ]);
curs=exec(conn, str1);
curs=fetch(curs);
InvestU = curs.Data;
% Input.InvestU=InvestU.InnerCode;
%% NonTradeable U
setdbprefs('datareturnformat','table')
str1=sprintf(['select cast(convert(varchar(8),A.TradingDay,112) as Int) as TradingDay,InnerCode  '...
    'from ShengYunDB..Info_Suspend A '...
    'order by TradingDay,InnerCode  '...
     ]);
curs=exec(conn, str1);
curs=fetch(curs);
NonTradeU = curs.Data;
NonTradeTime=unique(NonTradeU.TradingDay);
% Input.NonTradeU=NonTradeU.InnerCode;

%%
% Input.NonTradeU=OptPortOld(1:50,1);
%% Alpha & Risk
setdbprefs('datareturnformat','table')
str1=sprintf(['select TradingDay,InnerCode,TotalScore  '...
    'from ShengYunDB..StatFM_Info  '...
    'where TradingDay>=''%s'' '...
    'order by TradingDay,InnerCode  '...
    ],DateT);
curs=exec(conn, str1);
curs=fetch(curs);
Alpha = curs.Data;
AlphaRaw=[str2double(cellstr(datestr(datenum(Alpha.TradingDay,'yyyy-mm-dd'),'yyyymmdd'))),table2array(Alpha(:,2:3))];


%%
str1=sprintf(['select cast(convert(varchar(8),A.TradingDay,112) as Int) as TradingDay '...
    ',A.InnerCode '...
    ',A.FirstIndustryCode '...
    ',A.Size '...
    ',A.Beta '...
    ',A.ShortMomentum '...
    ',A.WeightedMomentum '...
    ',A.Vol '...
    ',A.Liquidity '...
    ',A.BP '...
    ',A.NLSIZE '...
    ',A.MktCap '...
    ',SpecificReturn '...
    ',SpecificSTD_LT '...
    ',case when left(B.SecuCode,1)=''6'' then 1 else 0 end as MktCode '...
    'from ShengYunDB..RM_StockRiskExposure A '...
    'left join ShengYunDB..StockDailyTrading B '...
    'on A.TradingDay=B.TradingDay and A.InnerCode=B.InnerCode '...
    'where  A.TradingDay>=''%s'' '...
    'order by A.TradingDay,A.InnerCode '...
    ],DateT);
curs=exec(conn, str1);
curs1=fetch(curs);
StockRiskRaw = curs1.Data;


%% Factor Risk
str1=sprintf(['select cast(convert(varchar(8),A.TradingDay,112) as Int) as TradingDay '...
    ',BP '...
    ',Beta '...
    ',Liquidity '...
    ',ShortMomentum '...
    ',Size '...
    ',Vol '...
    ',WeightedMomentum '...
    ',[Industry_10.0] as Industry_10 '...
    ',[Industry_11.0] as Industry_11 '...
    ',[Industry_12.0] as Industry_12 '...
    ',[Industry_20.0] as Industry_20 '...
    ',[Industry_21.0] as Industry_21 '...
    ',[Industry_22.0] as Industry_22 '...
    ',[Industry_23.0] as Industry_23 '...
    ',[Industry_24.0] as Industry_24 '...
    ',[Industry_25.0] as Industry_25 '...
    ',[Industry_26.0] as Industry_26 '...
    ',[Industry_27.0] as Industry_27 '...
    ',[Industry_28.0] as Industry_28 '...
    ',[Industry_30.0] as Industry_30 '...
    ',[Industry_31.0] as Industry_31 '...
    ',[Industry_32.0] as Industry_32 '...
    ',[Industry_33.0] as Industry_33 '...
    ',[Industry_34.0] as Industry_34 '...
    ',[Industry_35.0] as Industry_35 '...
    ',[Industry_36.0] as Industry_36 '...
    ',[Industry_37.0] as Industry_37 '...
    ',[Industry_40.0] as Industry_40 '...
    ',[Industry_41.0] as Industry_41 '...
    ',[Industry_42.0] as Industry_42 '...
    ',[Industry_50.0] as Industry_50 '...
    ',[Industry_60.0] as Industry_60 '...
    ',[Industry_61.0] as Industry_61 '...
    ',[Industry_62.0] as Industry_62 '...
    ',[Industry_63.0] as Industry_63 '...
    ',[Industry_70.0] as Industry_70 '...
    'from ShengYunDB..RM_FactorCorrelation_LT A '...
    'where  A.TradingDay>=''%s'' '...
    'order by TradingDay,Factor '...
    ],DateT);
curs=exec(conn, str1);
curs1=fetch(curs);
FactorCorrRaw = curs1.Data;


%
str1=sprintf(['select cast(convert(varchar(8),A.TradingDay,112) as Int) as TradingDay '...
    ',A.DailyReturn '...
    ',A.DailySTD_LT '...
    'from ShengYunDB..RM_FactorReturnRisk A '...
    'where Factor in (''Beta'',	''BP'',	''Industry_10.0'',	''Industry_11.0'',	''Industry_12.0'',	''Industry_20.0'',	''Industry_21.0'',	''Industry_22.0'',	''Industry_23.0'',	''Industry_24.0'',	''Industry_25.0'',	''Industry_26.0'',	''Industry_27.0'',	''Industry_28.0'',	''Industry_30.0'',	''Industry_31.0'',	''Industry_32.0'',	''Industry_33.0'',	''Industry_34.0'',	''Industry_35.0'',	''Industry_36.0'',	''Industry_37.0'',	''Industry_40.0'',	''Industry_41.0'',	''Industry_42.0'',	''Industry_50.0'',	''Industry_60.0'',	''Industry_61.0'',	''Industry_62.0'',	''Industry_63.0'',	''Industry_70.0'',	''Liquidity'',	''ShortMomentum'',	''Size'',	''Vol'',	''WeightedMomentum'') '...
    'AND  A.TradingDay >=''%s'' '...
    'order by TradingDay,Factor '...
    ],DateT);
curs=exec(conn, str1);
curs1=fetch(curs);
FactorRiskRaw = curs1.Data;

%%
TDList=unique(AlphaRaw(:,1));
NT=length(TDList);
[IndexW]=RM_get_HS300W();
H=3;
%%
for i1=1:H:length(NT)
    Input.Time=TDList(i1);
    InvestUIX=InvestU.TradingDay==Input.Time;
    Input.InvestU=InvestU.InnerCode(InvestUIX);
    
    SusTime=NonTradeTime(find(NonTradeTime<Input.Time,1,'last'));
    NonTradeIX=NonTradeU.TradingDay==SusTime;
    Input.NonTradeU=NonTradeU.InnerCode(NonTradeIX);
    
    AlphaIX=AlphaRaw(:,1)==Input.Time;
    Input.AlphaSignal=AlphaRaw(AlphaIX,:);
    
    BenchIX=IndexW(:,1)==Input.Time;
    Input.BenchMarkWeight=IndexW(BenchIX,:);
           
    StockRiskIX=StockRiskRaw.TradingDay==Input.Time;
    Input.Risks.StockRiskRaw=StockRiskRaw(StockRiskIX,:);
    
    FactorIX=FactorCorrRaw.TradingDay==Input.Time;
    Input.Risks.FactorCorrRaw=FactorCorrRaw(FactorIX,:);
    
    FactorIX=FactorRiskRaw.TradingDay==Input.Time;
    Input.Risks.FactorRiskRaw=FactorRiskRaw(FactorIX,:);
    
    OptSetUp=Optimizer_Cplex_Sus(Input);
    OptSetUp.Optimize();
    OptPort=OptSetUp.OptPort;
    Input.PreviousHolding=OptPort(:,2:3);
end