function [PortXX,RiskC]=get_port_active_exposures_LT(PortWeight,Bench,DateT)
%% Exposure Decom
PortWeight(:,1)=datenum(cellstr(num2str(PortWeight(:,1))),'yyyymmdd');

%%
[IndexR]=RM_get_IndexWT(Bench,DateT);
IndexW(:,1)=datenum(IndexR.TradingDay,'yyyy-mm-dd');
IndexW(:,2:3)=table2array(IndexR(:,2:3));
%%
conn=connect_jydb();
setdbprefs('datareturnformat','table')

str1=sprintf(['select A.TradingDay '...
    ',A.InnerCode '...
    ',A.FirstIndustryCode '...
    ',A.Size '...
    ',A.Beta '...
    ',A.ShortMomentum '...
    ',A.WeightedMomentum '...
    ',A.Vol '...
    ',A.Liquidity '...
    ',A.BP '...
    ',A.NLSIZE '...
    ',A.MktCap '...
    ',SpecificReturn '...
    ',SpecificSTD_LT '...
    'from ShengYunDB..RM_StockRiskExposure A '...
    'where  A.TradingDay=''%s'' '...
    'order by A.TradingDay,A.InnerCode '...
    ],DateT);
curs=exec(conn, str1);
curs1=fetch(curs);
StockRiskRawT = curs1.Data;
StockRiskRaw=datenum(StockRiskRawT.TradingDay,'yyyy-mm-dd');
StockRiskRaw=[StockRiskRaw,table2array(StockRiskRawT(:,2:end))];
clear StockRiskRawT
%% Factor Risk
str1=sprintf(['select A.TradingDay '...
    ',BP '...
    ',Beta '...
    ',Liquidity '...
    ',ShortMomentum '...
    ',Size '...
    ',Vol '...
    ',WeightedMomentum '...
    ',[Industry_10.0] '...
    ',[Industry_11.0] '...
    ',[Industry_12.0] '...
    ',[Industry_20.0] '...
    ',[Industry_21.0] '...
    ',[Industry_22.0] '...
    ',[Industry_23.0] '...
    ',[Industry_24.0] '...
    ',[Industry_25.0] '...
    ',[Industry_26.0] '...
    ',[Industry_27.0] '...
    ',[Industry_28.0] '...
    ',[Industry_30.0] '...
    ',[Industry_31.0] '...
    ',[Industry_32.0] '...
    ',[Industry_33.0] '...
    ',[Industry_34.0] '...
    ',[Industry_35.0] '...
    ',[Industry_36.0] '...
    ',[Industry_37.0] '...
    ',[Industry_40.0] '...
    ',[Industry_41.0] '...
    ',[Industry_42.0] '...
    ',[Industry_50.0] '...
    ',[Industry_60.0] '...
    ',[Industry_61.0] '...
    ',[Industry_62.0] '...
    ',[Industry_63.0] '...
    ',[Industry_70.0] '...
    'from ShengYunDB..RM_FactorCorrelation_LT A '...
     'where  A.TradingDay=''%s'' '...
    'order by TradingDay,Factor '...
    
    ],DateT);
curs=exec(conn, str1);
curs1=fetch(curs);
FactorCorrRawT = curs1.Data;
FactorCorrRaw=datenum(FactorCorrRawT.TradingDay,'yyyy-mm-dd');
FactorCorrRaw=[FactorCorrRaw,table2array(FactorCorrRawT(:,2:end))];
clear FactorCorrRawT
%%
str1=sprintf(['select A.TradingDay '...
    ',A.DailyReturn '...
    ',A.DailySTD_LT '...
    'from ShengYunDB..RM_FactorReturnRisk A '...
    'where Factor in (''Beta'',	''BP'',	''Industry_10.0'',	''Industry_11.0'',	''Industry_12.0'',	''Industry_20.0'',	''Industry_21.0'',	''Industry_22.0'',	''Industry_23.0'',	''Industry_24.0'',	''Industry_25.0'',	''Industry_26.0'',	''Industry_27.0'',	''Industry_28.0'',	''Industry_30.0'',	''Industry_31.0'',	''Industry_32.0'',	''Industry_33.0'',	''Industry_34.0'',	''Industry_35.0'',	''Industry_36.0'',	''Industry_37.0'',	''Industry_40.0'',	''Industry_41.0'',	''Industry_42.0'',	''Industry_50.0'',	''Industry_60.0'',	''Industry_61.0'',	''Industry_62.0'',	''Industry_63.0'',	''Industry_70.0'',	''Liquidity'',	''ShortMomentum'',	''Size'',	''Vol'',	''WeightedMomentum'') '...
    'and A.TradingDay=''%s'' '...
    'order by TradingDay,Factor '...
     ],DateT);
curs=exec(conn, str1);
curs1=fetch(curs);
FactorRiskRawT = curs1.Data;
FactorRiskRaw=datenum(FactorRiskRawT.TradingDay,'yyyy-mm-dd');
FactorRiskRaw=[FactorRiskRaw,table2array(FactorRiskRawT(:,2:end))];
clear FactorRiskRawT
%%
load('E:\work\riskmodel\Opt_port_update_since20150201.mat', 'IndList')
T=datenum(DateT,'yyyy-mm-dd');
PortX=[];
ForecastRisk=nan;
IndRisk=ForecastRisk;
StyleRisk=ForecastRisk;
SpecificRisk=ForecastRisk;

try
    PortC=PortWeight(:,2:3);
    BenchC=IndexW(IndexW(:,1)==T,2:3);
    BenchC(:,2)=BenchC(:,2)/sum(BenchC(:,2));
    CodeU=union(PortC(:,1),BenchC(:,1));
    WC=zeros(length(CodeU),2);
    [~,I1]=ismember(PortC(:,1),CodeU);
    [~,I2]=ismember(BenchC(:,1),CodeU);
    WC(I1,1)=PortC(:,2);
    WC(I2,2)=BenchC(:,2);
    ActW=WC(:,1)-WC(:,2);
    
    LP=length(CodeU);
    StockRiskIX=StockRiskRaw(:,1)==T;
    StockRiskC=StockRiskRaw(StockRiskIX,2:end);
    StyleExp=nan(LP,7);
    [~,IA,IB]=intersect(StockRiskC(:,1),CodeU,'stable');
    StyleExp(IB,:)=StockRiskC(IA,[9,4,8,5,3,7,6]);
    StyleExp(isnan(StyleExp))=0;
    
    IndC=zeros(LP,1);
    IndC(IB)=StockRiskC(IA,2);
    IndExp=RM_get_Ind_dummy(IndC,IndList);
    
    X=[StyleExp,IndExp];
    StockDelta=nan(LP,1);
    StockDelta(IB)=StockRiskC(IA,end);
    INA=isnan(StockDelta);
    StockDelta(INA)=mean(StockDelta(~INA));
    
    FactorIX=FactorCorrRaw(:,1)==T;
    FactorCor=FactorCorrRaw(FactorIX,2:end);
    FactorCor=FactorCor([2,1,32:36,3:31],:);
    
    FactorIX=FactorRiskRaw(:,1)==T;
    FactorStd=FactorRiskRaw(FactorIX,3);
    FactorStd=FactorStd([2,1,32:36,3:31],:);
    
    FactorCov=FactorCor.*(FactorStd*FactorStd');
    
    PortXC=X'*ActW;
    PortX=[PortX;PortXC'];
    
    DeltaC=StockDelta;
    ForecastRisk=(ActW'*(X*FactorCov*X'+diag(DeltaC.^2))*ActW)^0.5*250^0.5;
    IndMat=FactorCov(8:end,8:end);
    StyleMat=FactorCov(1:7,1:7);
    IndRisk=(ActW'*(X(:,8:end)*IndMat*X(:,8:end)')*ActW)^0.5*250^0.5;
    StyleRisk=(ActW'*(X(:,1:7)*StyleMat*X(:,1:7)')*ActW)^0.5*250^0.5;
    SpecificRisk=(ActW'*(diag(DeltaC.^2))*ActW)^0.5*250^0.5;
catch err
end

%%
PortXX=PortX';
RiskC=[ForecastRisk;IndRisk;StyleRisk;SpecificRisk];